# Option-1 : Creating docker container using command module 
---
- hosts: all
  become: true

  tasks:
  - name: Creating docker image using docker command
    command: docker run -d --name resume-generator-container -p 8080:8080 resume-generator:v1.0.0
	
# option-2 : Creating docker container using docker_container module 	
#  tasks:
#  - name: Create resume-generator-container
#    docker_container:
#      name: resume-generator-container
#      image: resume-generator
#      state: present
#      recreate: yes
#      ports:
#        - "8080:8080"
