---
- hosts: all
  become: true
  tasks:
  - name: Stop if we have old docker container
    command: docker stop resume-generator-container
    ignore_errors: yes

  - name: Remove stopped docker container
    command: docker rm resume-generator-container
    ignore_errors: yes

  - name: Remove current docker image
    command: docker rmi resume-generator:v1.0.0
    ignore_errors: yes
#    register: result
#    failed_when:
#      - result.rc == 0
#      - '"docker" not in result.stdout'


  - name: Building docker image
    command: docker build -t resume-generator:v1.0.0 .
    args:
      chdir: /opt/docker

  - name: Creating docker image
    command: docker run -d --name resume-generator-container -p 8080:8080 resume-generator:v1.0.0

